### ISSUE TITLE
Dictionary download unsuccessful.

### ISSUE THREAD

**Issue by InoueKenta** [ispedals/FloatingJapaneseDictionary#1]
Well, when I try to cut off the internet, it seem that the app can't launch again. 
In console logcat:
"pedals.is.floatingjapanesedictionary D/FloatingJapaneseDictionaryLauncherActivity﹕ we are currently downloading a dictionary"
I think you should fix this bug.

**Comment by ispedals** [comment]
The dictionary is now embedded in the app, so this should no longer occur.

**Comment by fireheart251** [comment]
I have Android 6.1 but I can't install this. Does my phone need to be rooted or something?
